export const UPDATE_SUBURB = 'UPDATE_SUBURB';
export const UPDATE_SCALE_BY = 'UPDATE_SCALE_BY';
export const UPDATE_CAPACITY = 'UPDATE_CAPACITY';
export const UPDATE_BUDGET = 'UPDATE_BUDGET';
export const UPDATE_YEAR = 'UPDATE_YEAR';
export const UPDATE_DAYS = 'UPDATE_DAYS';
export const UPDATE_QUALITY = 'UPDATE_QUALITY';